/**
 * Comprehensive audit event types for healthcare platform
 * Covers HIPAA compliance, security, and operational requirements
 */
export enum AuditEventType {
  // Authentication Events
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  MFA_FAILED = 'MFA_FAILED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',

  // Data Access Events (HIPAA Critical)
  PATIENT_DATA_VIEWED = 'PATIENT_DATA_VIEWED',
  PATIENT_DATA_CREATED = 'PATIENT_DATA_CREATED',
  PATIENT_DATA_UPDATED = 'PATIENT_DATA_UPDATED',
  PATIENT_DATA_DELETED = 'PATIENT_DATA_DELETED',
  PATIENT_DATA_EXPORTED = 'PATIENT_DATA_EXPORTED',
  PATIENT_SEARCH_PERFORMED = 'PATIENT_SEARCH_PERFORMED',
  MEDICAL_RECORD_ACCESSED = 'MEDICAL_RECORD_ACCESSED',
  MEDICAL_RECORD_MODIFIED = 'MEDICAL_RECORD_MODIFIED',
  CLINICAL_NOTES_VIEWED = 'CLINICAL_NOTES_VIEWED',
  CLINICAL_NOTES_CREATED = 'CLINICAL_NOTES_CREATED',
  CLINICAL_NOTES_UPDATED = 'CLINICAL_NOTES_UPDATED',
  LAB_RESULTS_ACCESSED = 'LAB_RESULTS_ACCESSED',
  PRESCRIPTION_ACCESSED = 'PRESCRIPTION_ACCESSED',
  IMAGING_ACCESSED = 'IMAGING_ACCESSED',

  // Administrative Events
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_REACTIVATED = 'USER_REACTIVATED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  ADMIN_IMPERSONATION_STARTED = 'ADMIN_IMPERSONATION_STARTED',
  ADMIN_IMPERSONATION_ENDED = 'ADMIN_IMPERSONATION_ENDED',
  SYSTEM_CONFIGURATION_CHANGED = 'SYSTEM_CONFIGURATION_CHANGED',
  BACKUP_CREATED = 'BACKUP_CREATED',
  BACKUP_RESTORED = 'BACKUP_RESTORED',

  // Security Events
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  CSRF_DETECTED = 'CSRF_DETECTED',
  SQL_INJECTION_ATTEMPT = 'SQL_INJECTION_ATTEMPT',
  XSS_ATTEMPT = 'XSS_ATTEMPT',
  BRUTE_FORCE_ATTEMPT = 'BRUTE_FORCE_ATTEMPT',
  PRIVILEGE_ESCALATION_ATTEMPT = 'PRIVILEGE_ESCALATION_ATTEMPT',
  DATA_BREACH_DETECTED = 'DATA_BREACH_DETECTED',
  SECURITY_POLICY_VIOLATION = 'SECURITY_POLICY_VIOLATION',

  // File and Document Events
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DOWNLOADED = 'FILE_DOWNLOADED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_SHARED = 'FILE_SHARED',
  DOCUMENT_PRINTED = 'DOCUMENT_PRINTED',
  DOCUMENT_EMAILED = 'DOCUMENT_EMAILED',
  DOCUMENT_FAXED = 'DOCUMENT_FAXED',

  // Communication Events
  MESSAGE_SENT = 'MESSAGE_SENT',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  EMAIL_SENT = 'EMAIL_SENT',
  SMS_SENT = 'SMS_SENT',
  APPOINTMENT_REMINDER_SENT = 'APPOINTMENT_REMINDER_SENT',
  COMMUNICATION_CONSENT_UPDATED = 'COMMUNICATION_CONSENT_UPDATED',

  // Appointment and Scheduling Events
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_CHECKED_IN = 'APPOINTMENT_CHECKED_IN',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  SCHEDULE_ACCESSED = 'SCHEDULE_ACCESSED',

  // Billing and Financial Events
  INVOICE_CREATED = 'INVOICE_CREATED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  BILLING_INFORMATION_UPDATED = 'BILLING_INFORMATION_UPDATED',
  INSURANCE_CLAIM_SUBMITTED = 'INSURANCE_CLAIM_SUBMITTED',

  // System Events
  SYSTEM_STARTUP = 'SYSTEM_STARTUP',
  SYSTEM_SHUTDOWN = 'SYSTEM_SHUTDOWN',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  API_RATE_LIMIT_CONFIGURED = 'API_RATE_LIMIT_CONFIGURED',
  MAINTENANCE_MODE_ENABLED = 'MAINTENANCE_MODE_ENABLED',
  MAINTENANCE_MODE_DISABLED = 'MAINTENANCE_MODE_DISABLED',

  // Compliance and Audit Events
  AUDIT_LOG_ACCESSED = 'AUDIT_LOG_ACCESSED',
  AUDIT_LOG_EXPORTED = 'AUDIT_LOG_EXPORTED',
  COMPLIANCE_REPORT_GENERATED = 'COMPLIANCE_REPORT_GENERATED',
  DATA_RETENTION_POLICY_APPLIED = 'DATA_RETENTION_POLICY_APPLIED',
  GDPR_REQUEST_RECEIVED = 'GDPR_REQUEST_RECEIVED',
  HIPAA_VIOLATION_DETECTED = 'HIPAA_VIOLATION_DETECTED',
  BREACH_NOTIFICATION_SENT = 'BREACH_NOTIFICATION_SENT',

  // Integration Events
  EXTERNAL_API_CALLED = 'EXTERNAL_API_CALLED',
  EXTERNAL_API_FAILED = 'EXTERNAL_API_FAILED',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  DATA_SYNC_STARTED = 'DATA_SYNC_STARTED',
  DATA_SYNC_COMPLETED = 'DATA_SYNC_COMPLETED',
  DATA_SYNC_FAILED = 'DATA_SYNC_FAILED',

  // AI and Analytics Events
  AI_MODEL_ACCESSED = 'AI_MODEL_ACCESSED',
  AI_PREDICTION_MADE = 'AI_PREDICTION_MADE',
  ANALYTICS_REPORT_VIEWED = 'ANALYTICS_REPORT_VIEWED',
  DATA_ANALYSIS_PERFORMED = 'DATA_ANALYSIS_PERFORMED',
}

/**
 * Categories for grouping related audit events
 */
export enum AuditCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  DATA_ACCESS = 'DATA_ACCESS',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  SECURITY = 'SECURITY',
  SYSTEM = 'SYSTEM',
  COMMUNICATION = 'COMMUNICATION',
  FINANCIAL = 'FINANCIAL',
  COMPLIANCE = 'COMPLIANCE',
  INTEGRATION = 'INTEGRATION',
  CLINICAL = 'CLINICAL',
  FILE_MANAGEMENT = 'FILE_MANAGEMENT',
  AI_ANALYTICS = 'AI_ANALYTICS',
}

/**
 * Severity levels for audit events
 */
export enum AuditSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

/**
 * Risk levels for security assessment
 */
export enum RiskLevel {
  MINIMAL = 'MINIMAL',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  SEVERE = 'SEVERE',
  CRITICAL = 'CRITICAL',
}

/**
 * Compliance frameworks
 */
export enum ComplianceFramework {
  HIPAA = 'HIPAA',
  GDPR = 'GDPR',
  SOX = 'SOX',
  PCI_DSS = 'PCI_DSS',
  HITECH = 'HITECH',
  FERPA = 'FERPA',
  SOC2 = 'SOC2',
}

/**
 * Device types for client identification
 */
export enum DeviceType {
  DESKTOP = 'DESKTOP',
  MOBILE = 'MOBILE',
  TABLET = 'TABLET',
  KIOSK = 'KIOSK',
  API_CLIENT = 'API_CLIENT',
  UNKNOWN = 'UNKNOWN',
}