"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditSearchDto = void 0;
const class_validator_1 = require("class-validator");
const class_transformer_1 = require("class-transformer");
const audit_enums_1 = require("../enums/audit.enums");
let AuditSearchDto = (() => {
    var _a;
    let _startDate_decorators;
    let _startDate_initializers = [];
    let _startDate_extraInitializers = [];
    let _endDate_decorators;
    let _endDate_initializers = [];
    let _endDate_extraInitializers = [];
    let _userId_decorators;
    let _userId_initializers = [];
    let _userId_extraInitializers = [];
    let _patientId_decorators;
    let _patientId_initializers = [];
    let _patientId_extraInitializers = [];
    let _userRole_decorators;
    let _userRole_initializers = [];
    let _userRole_extraInitializers = [];
    let _eventType_decorators;
    let _eventType_initializers = [];
    let _eventType_extraInitializers = [];
    let _category_decorators;
    let _category_initializers = [];
    let _category_extraInitializers = [];
    let _severity_decorators;
    let _severity_initializers = [];
    let _severity_extraInitializers = [];
    let _riskLevel_decorators;
    let _riskLevel_initializers = [];
    let _riskLevel_extraInitializers = [];
    let _resourceType_decorators;
    let _resourceType_initializers = [];
    let _resourceType_extraInitializers = [];
    let _resourceId_decorators;
    let _resourceId_initializers = [];
    let _resourceId_extraInitializers = [];
    let _ipAddress_decorators;
    let _ipAddress_initializers = [];
    let _ipAddress_extraInitializers = [];
    let _endpoint_decorators;
    let _endpoint_initializers = [];
    let _endpoint_extraInitializers = [];
    let _httpMethod_decorators;
    let _httpMethod_initializers = [];
    let _httpMethod_extraInitializers = [];
    let _sessionId_decorators;
    let _sessionId_initializers = [];
    let _sessionId_extraInitializers = [];
    let _correlationId_decorators;
    let _correlationId_initializers = [];
    let _correlationId_extraInitializers = [];
    let _sourceSystem_decorators;
    let _sourceSystem_initializers = [];
    let _sourceSystem_extraInitializers = [];
    let _requiresAlert_decorators;
    let _requiresAlert_initializers = [];
    let _requiresAlert_extraInitializers = [];
    let _reviewed_decorators;
    let _reviewed_initializers = [];
    let _reviewed_extraInitializers = [];
    let _suspiciousActivity_decorators;
    let _suspiciousActivity_initializers = [];
    let _suspiciousActivity_extraInitializers = [];
    let _dataExported_decorators;
    let _dataExported_initializers = [];
    let _dataExported_extraInitializers = [];
    let _includeInComplianceReport_decorators;
    let _includeInComplianceReport_initializers = [];
    let _includeInComplianceReport_extraInitializers = [];
    let _description_decorators;
    let _description_initializers = [];
    let _description_extraInitializers = [];
    let _page_decorators;
    let _page_initializers = [];
    let _page_extraInitializers = [];
    let _limit_decorators;
    let _limit_initializers = [];
    let _limit_extraInitializers = [];
    let _sortBy_decorators;
    let _sortBy_initializers = [];
    let _sortBy_extraInitializers = [];
    let _sortOrder_decorators;
    let _sortOrder_initializers = [];
    let _sortOrder_extraInitializers = [];
    let _searchTerm_decorators;
    let _searchTerm_initializers = [];
    let _searchTerm_extraInitializers = [];
    let _minResponseTime_decorators;
    let _minResponseTime_initializers = [];
    let _minResponseTime_extraInitializers = [];
    let _maxResponseTime_decorators;
    let _maxResponseTime_initializers = [];
    let _maxResponseTime_extraInitializers = [];
    let _minRecordsAffected_decorators;
    let _minRecordsAffected_initializers = [];
    let _minRecordsAffected_extraInitializers = [];
    let _maxRecordsAffected_decorators;
    let _maxRecordsAffected_initializers = [];
    let _maxRecordsAffected_extraInitializers = [];
    let _deviceType_decorators;
    let _deviceType_initializers = [];
    let _deviceType_extraInitializers = [];
    let _clientApplication_decorators;
    let _clientApplication_initializers = [];
    let _clientApplication_extraInitializers = [];
    let _geolocation_decorators;
    let _geolocation_initializers = [];
    let _geolocation_extraInitializers = [];
    let _timeRange_decorators;
    let _timeRange_initializers = [];
    let _timeRange_extraInitializers = [];
    let _accessPurpose_decorators;
    let _accessPurpose_initializers = [];
    let _accessPurpose_extraInitializers = [];
    let _minimumNecessary_decorators;
    let _minimumNecessary_initializers = [];
    let _minimumNecessary_extraInitializers = [];
    let _patientConsent_decorators;
    let _patientConsent_initializers = [];
    let _patientConsent_extraInitializers = [];
    let _emergencyAccess_decorators;
    let _emergencyAccess_initializers = [];
    let _emergencyAccess_extraInitializers = [];
    let _exportFormat_decorators;
    let _exportFormat_initializers = [];
    let _exportFormat_extraInitializers = [];
    let _includeAdditionalData_decorators;
    let _includeAdditionalData_initializers = [];
    let _includeAdditionalData_extraInitializers = [];
    let _anonymizePatientData_decorators;
    let _anonymizePatientData_initializers = [];
    let _anonymizePatientData_extraInitializers = [];
    return _a = class AuditSearchDto {
            constructor() {
                this.startDate = __runInitializers(this, _startDate_initializers, void 0);
                this.endDate = (__runInitializers(this, _startDate_extraInitializers), __runInitializers(this, _endDate_initializers, void 0));
                this.userId = (__runInitializers(this, _endDate_extraInitializers), __runInitializers(this, _userId_initializers, void 0));
                this.patientId = (__runInitializers(this, _userId_extraInitializers), __runInitializers(this, _patientId_initializers, void 0));
                this.userRole = (__runInitializers(this, _patientId_extraInitializers), __runInitializers(this, _userRole_initializers, void 0));
                this.eventType = (__runInitializers(this, _userRole_extraInitializers), __runInitializers(this, _eventType_initializers, void 0));
                this.category = (__runInitializers(this, _eventType_extraInitializers), __runInitializers(this, _category_initializers, void 0));
                this.severity = (__runInitializers(this, _category_extraInitializers), __runInitializers(this, _severity_initializers, void 0));
                this.riskLevel = (__runInitializers(this, _severity_extraInitializers), __runInitializers(this, _riskLevel_initializers, void 0));
                this.resourceType = (__runInitializers(this, _riskLevel_extraInitializers), __runInitializers(this, _resourceType_initializers, void 0));
                this.resourceId = (__runInitializers(this, _resourceType_extraInitializers), __runInitializers(this, _resourceId_initializers, void 0));
                this.ipAddress = (__runInitializers(this, _resourceId_extraInitializers), __runInitializers(this, _ipAddress_initializers, void 0));
                this.endpoint = (__runInitializers(this, _ipAddress_extraInitializers), __runInitializers(this, _endpoint_initializers, void 0));
                this.httpMethod = (__runInitializers(this, _endpoint_extraInitializers), __runInitializers(this, _httpMethod_initializers, void 0));
                this.sessionId = (__runInitializers(this, _httpMethod_extraInitializers), __runInitializers(this, _sessionId_initializers, void 0));
                this.correlationId = (__runInitializers(this, _sessionId_extraInitializers), __runInitializers(this, _correlationId_initializers, void 0));
                this.sourceSystem = (__runInitializers(this, _correlationId_extraInitializers), __runInitializers(this, _sourceSystem_initializers, void 0));
                this.requiresAlert = (__runInitializers(this, _sourceSystem_extraInitializers), __runInitializers(this, _requiresAlert_initializers, void 0));
                this.reviewed = (__runInitializers(this, _requiresAlert_extraInitializers), __runInitializers(this, _reviewed_initializers, void 0));
                this.suspiciousActivity = (__runInitializers(this, _reviewed_extraInitializers), __runInitializers(this, _suspiciousActivity_initializers, void 0));
                this.dataExported = (__runInitializers(this, _suspiciousActivity_extraInitializers), __runInitializers(this, _dataExported_initializers, void 0));
                this.includeInComplianceReport = (__runInitializers(this, _dataExported_extraInitializers), __runInitializers(this, _includeInComplianceReport_initializers, void 0));
                this.description = (__runInitializers(this, _includeInComplianceReport_extraInitializers), __runInitializers(this, _description_initializers, void 0));
                this.page = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _page_initializers, 1));
                this.limit = (__runInitializers(this, _page_extraInitializers), __runInitializers(this, _limit_initializers, 50));
                this.sortBy = (__runInitializers(this, _limit_extraInitializers), __runInitializers(this, _sortBy_initializers, 'timestamp'));
                this.sortOrder = (__runInitializers(this, _sortBy_extraInitializers), __runInitializers(this, _sortOrder_initializers, 'DESC'));
                this.searchTerm = (__runInitializers(this, _sortOrder_extraInitializers), __runInitializers(this, _searchTerm_initializers, void 0));
                // Additional filters for advanced searching
                this.minResponseTime = (__runInitializers(this, _searchTerm_extraInitializers), __runInitializers(this, _minResponseTime_initializers, void 0));
                this.maxResponseTime = (__runInitializers(this, _minResponseTime_extraInitializers), __runInitializers(this, _maxResponseTime_initializers, void 0));
                this.minRecordsAffected = (__runInitializers(this, _maxResponseTime_extraInitializers), __runInitializers(this, _minRecordsAffected_initializers, void 0));
                this.maxRecordsAffected = (__runInitializers(this, _minRecordsAffected_extraInitializers), __runInitializers(this, _maxRecordsAffected_initializers, void 0));
                this.deviceType = (__runInitializers(this, _maxRecordsAffected_extraInitializers), __runInitializers(this, _deviceType_initializers, void 0));
                this.clientApplication = (__runInitializers(this, _deviceType_extraInitializers), __runInitializers(this, _clientApplication_initializers, void 0));
                this.geolocation = (__runInitializers(this, _clientApplication_extraInitializers), __runInitializers(this, _geolocation_initializers, void 0));
                // Time-based filters
                this.timeRange = (__runInitializers(this, _geolocation_extraInitializers), __runInitializers(this, _timeRange_initializers, void 0));
                // HIPAA-specific filters
                this.accessPurpose = (__runInitializers(this, _timeRange_extraInitializers), __runInitializers(this, _accessPurpose_initializers, void 0));
                this.minimumNecessary = (__runInitializers(this, _accessPurpose_extraInitializers), __runInitializers(this, _minimumNecessary_initializers, void 0));
                this.patientConsent = (__runInitializers(this, _minimumNecessary_extraInitializers), __runInitializers(this, _patientConsent_initializers, void 0));
                this.emergencyAccess = (__runInitializers(this, _patientConsent_extraInitializers), __runInitializers(this, _emergencyAccess_initializers, void 0));
                // Export options
                this.exportFormat = (__runInitializers(this, _emergencyAccess_extraInitializers), __runInitializers(this, _exportFormat_initializers, void 0));
                this.includeAdditionalData = (__runInitializers(this, _exportFormat_extraInitializers), __runInitializers(this, _includeAdditionalData_initializers, void 0));
                this.anonymizePatientData = (__runInitializers(this, _includeAdditionalData_extraInitializers), __runInitializers(this, _anonymizePatientData_initializers, void 0));
                __runInitializers(this, _anonymizePatientData_extraInitializers);
            }
        },
        (() => {
            const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _startDate_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsDateString)()];
            _endDate_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsDateString)()];
            _userId_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsUUID)()];
            _patientId_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsUUID)()];
            _userRole_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _eventType_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(audit_enums_1.AuditEventType)];
            _category_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(audit_enums_1.AuditCategory)];
            _severity_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(audit_enums_1.AuditSeverity)];
            _riskLevel_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(audit_enums_1.RiskLevel)];
            _resourceType_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _resourceId_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _ipAddress_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsIP)()];
            _endpoint_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _httpMethod_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _sessionId_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _correlationId_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _sourceSystem_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _requiresAlert_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _reviewed_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _suspiciousActivity_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _dataExported_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _includeInComplianceReport_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _description_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _page_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Type)(() => Number), (0, class_validator_1.IsNumber)(), (0, class_validator_1.Min)(1)];
            _limit_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Type)(() => Number), (0, class_validator_1.IsNumber)(), (0, class_validator_1.Min)(1), (0, class_validator_1.Max)(1000)];
            _sortBy_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _sortOrder_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(['ASC', 'DESC'])];
            _searchTerm_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _minResponseTime_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Type)(() => Number), (0, class_validator_1.IsNumber)()];
            _maxResponseTime_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Type)(() => Number), (0, class_validator_1.IsNumber)()];
            _minRecordsAffected_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Type)(() => Number), (0, class_validator_1.IsNumber)()];
            _maxRecordsAffected_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Type)(() => Number), (0, class_validator_1.IsNumber)()];
            _deviceType_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _clientApplication_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _geolocation_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _timeRange_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _accessPurpose_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _minimumNecessary_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _patientConsent_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _emergencyAccess_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _exportFormat_decorators = [(0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(['json', 'csv', 'pdf'])];
            _includeAdditionalData_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            _anonymizePatientData_decorators = [(0, class_validator_1.IsOptional)(), (0, class_transformer_1.Transform)(({ value }) => value === 'true' || value === true)];
            __esDecorate(null, null, _startDate_decorators, { kind: "field", name: "startDate", static: false, private: false, access: { has: obj => "startDate" in obj, get: obj => obj.startDate, set: (obj, value) => { obj.startDate = value; } }, metadata: _metadata }, _startDate_initializers, _startDate_extraInitializers);
            __esDecorate(null, null, _endDate_decorators, { kind: "field", name: "endDate", static: false, private: false, access: { has: obj => "endDate" in obj, get: obj => obj.endDate, set: (obj, value) => { obj.endDate = value; } }, metadata: _metadata }, _endDate_initializers, _endDate_extraInitializers);
            __esDecorate(null, null, _userId_decorators, { kind: "field", name: "userId", static: false, private: false, access: { has: obj => "userId" in obj, get: obj => obj.userId, set: (obj, value) => { obj.userId = value; } }, metadata: _metadata }, _userId_initializers, _userId_extraInitializers);
            __esDecorate(null, null, _patientId_decorators, { kind: "field", name: "patientId", static: false, private: false, access: { has: obj => "patientId" in obj, get: obj => obj.patientId, set: (obj, value) => { obj.patientId = value; } }, metadata: _metadata }, _patientId_initializers, _patientId_extraInitializers);
            __esDecorate(null, null, _userRole_decorators, { kind: "field", name: "userRole", static: false, private: false, access: { has: obj => "userRole" in obj, get: obj => obj.userRole, set: (obj, value) => { obj.userRole = value; } }, metadata: _metadata }, _userRole_initializers, _userRole_extraInitializers);
            __esDecorate(null, null, _eventType_decorators, { kind: "field", name: "eventType", static: false, private: false, access: { has: obj => "eventType" in obj, get: obj => obj.eventType, set: (obj, value) => { obj.eventType = value; } }, metadata: _metadata }, _eventType_initializers, _eventType_extraInitializers);
            __esDecorate(null, null, _category_decorators, { kind: "field", name: "category", static: false, private: false, access: { has: obj => "category" in obj, get: obj => obj.category, set: (obj, value) => { obj.category = value; } }, metadata: _metadata }, _category_initializers, _category_extraInitializers);
            __esDecorate(null, null, _severity_decorators, { kind: "field", name: "severity", static: false, private: false, access: { has: obj => "severity" in obj, get: obj => obj.severity, set: (obj, value) => { obj.severity = value; } }, metadata: _metadata }, _severity_initializers, _severity_extraInitializers);
            __esDecorate(null, null, _riskLevel_decorators, { kind: "field", name: "riskLevel", static: false, private: false, access: { has: obj => "riskLevel" in obj, get: obj => obj.riskLevel, set: (obj, value) => { obj.riskLevel = value; } }, metadata: _metadata }, _riskLevel_initializers, _riskLevel_extraInitializers);
            __esDecorate(null, null, _resourceType_decorators, { kind: "field", name: "resourceType", static: false, private: false, access: { has: obj => "resourceType" in obj, get: obj => obj.resourceType, set: (obj, value) => { obj.resourceType = value; } }, metadata: _metadata }, _resourceType_initializers, _resourceType_extraInitializers);
            __esDecorate(null, null, _resourceId_decorators, { kind: "field", name: "resourceId", static: false, private: false, access: { has: obj => "resourceId" in obj, get: obj => obj.resourceId, set: (obj, value) => { obj.resourceId = value; } }, metadata: _metadata }, _resourceId_initializers, _resourceId_extraInitializers);
            __esDecorate(null, null, _ipAddress_decorators, { kind: "field", name: "ipAddress", static: false, private: false, access: { has: obj => "ipAddress" in obj, get: obj => obj.ipAddress, set: (obj, value) => { obj.ipAddress = value; } }, metadata: _metadata }, _ipAddress_initializers, _ipAddress_extraInitializers);
            __esDecorate(null, null, _endpoint_decorators, { kind: "field", name: "endpoint", static: false, private: false, access: { has: obj => "endpoint" in obj, get: obj => obj.endpoint, set: (obj, value) => { obj.endpoint = value; } }, metadata: _metadata }, _endpoint_initializers, _endpoint_extraInitializers);
            __esDecorate(null, null, _httpMethod_decorators, { kind: "field", name: "httpMethod", static: false, private: false, access: { has: obj => "httpMethod" in obj, get: obj => obj.httpMethod, set: (obj, value) => { obj.httpMethod = value; } }, metadata: _metadata }, _httpMethod_initializers, _httpMethod_extraInitializers);
            __esDecorate(null, null, _sessionId_decorators, { kind: "field", name: "sessionId", static: false, private: false, access: { has: obj => "sessionId" in obj, get: obj => obj.sessionId, set: (obj, value) => { obj.sessionId = value; } }, metadata: _metadata }, _sessionId_initializers, _sessionId_extraInitializers);
            __esDecorate(null, null, _correlationId_decorators, { kind: "field", name: "correlationId", static: false, private: false, access: { has: obj => "correlationId" in obj, get: obj => obj.correlationId, set: (obj, value) => { obj.correlationId = value; } }, metadata: _metadata }, _correlationId_initializers, _correlationId_extraInitializers);
            __esDecorate(null, null, _sourceSystem_decorators, { kind: "field", name: "sourceSystem", static: false, private: false, access: { has: obj => "sourceSystem" in obj, get: obj => obj.sourceSystem, set: (obj, value) => { obj.sourceSystem = value; } }, metadata: _metadata }, _sourceSystem_initializers, _sourceSystem_extraInitializers);
            __esDecorate(null, null, _requiresAlert_decorators, { kind: "field", name: "requiresAlert", static: false, private: false, access: { has: obj => "requiresAlert" in obj, get: obj => obj.requiresAlert, set: (obj, value) => { obj.requiresAlert = value; } }, metadata: _metadata }, _requiresAlert_initializers, _requiresAlert_extraInitializers);
            __esDecorate(null, null, _reviewed_decorators, { kind: "field", name: "reviewed", static: false, private: false, access: { has: obj => "reviewed" in obj, get: obj => obj.reviewed, set: (obj, value) => { obj.reviewed = value; } }, metadata: _metadata }, _reviewed_initializers, _reviewed_extraInitializers);
            __esDecorate(null, null, _suspiciousActivity_decorators, { kind: "field", name: "suspiciousActivity", static: false, private: false, access: { has: obj => "suspiciousActivity" in obj, get: obj => obj.suspiciousActivity, set: (obj, value) => { obj.suspiciousActivity = value; } }, metadata: _metadata }, _suspiciousActivity_initializers, _suspiciousActivity_extraInitializers);
            __esDecorate(null, null, _dataExported_decorators, { kind: "field", name: "dataExported", static: false, private: false, access: { has: obj => "dataExported" in obj, get: obj => obj.dataExported, set: (obj, value) => { obj.dataExported = value; } }, metadata: _metadata }, _dataExported_initializers, _dataExported_extraInitializers);
            __esDecorate(null, null, _includeInComplianceReport_decorators, { kind: "field", name: "includeInComplianceReport", static: false, private: false, access: { has: obj => "includeInComplianceReport" in obj, get: obj => obj.includeInComplianceReport, set: (obj, value) => { obj.includeInComplianceReport = value; } }, metadata: _metadata }, _includeInComplianceReport_initializers, _includeInComplianceReport_extraInitializers);
            __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: obj => "description" in obj, get: obj => obj.description, set: (obj, value) => { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
            __esDecorate(null, null, _page_decorators, { kind: "field", name: "page", static: false, private: false, access: { has: obj => "page" in obj, get: obj => obj.page, set: (obj, value) => { obj.page = value; } }, metadata: _metadata }, _page_initializers, _page_extraInitializers);
            __esDecorate(null, null, _limit_decorators, { kind: "field", name: "limit", static: false, private: false, access: { has: obj => "limit" in obj, get: obj => obj.limit, set: (obj, value) => { obj.limit = value; } }, metadata: _metadata }, _limit_initializers, _limit_extraInitializers);
            __esDecorate(null, null, _sortBy_decorators, { kind: "field", name: "sortBy", static: false, private: false, access: { has: obj => "sortBy" in obj, get: obj => obj.sortBy, set: (obj, value) => { obj.sortBy = value; } }, metadata: _metadata }, _sortBy_initializers, _sortBy_extraInitializers);
            __esDecorate(null, null, _sortOrder_decorators, { kind: "field", name: "sortOrder", static: false, private: false, access: { has: obj => "sortOrder" in obj, get: obj => obj.sortOrder, set: (obj, value) => { obj.sortOrder = value; } }, metadata: _metadata }, _sortOrder_initializers, _sortOrder_extraInitializers);
            __esDecorate(null, null, _searchTerm_decorators, { kind: "field", name: "searchTerm", static: false, private: false, access: { has: obj => "searchTerm" in obj, get: obj => obj.searchTerm, set: (obj, value) => { obj.searchTerm = value; } }, metadata: _metadata }, _searchTerm_initializers, _searchTerm_extraInitializers);
            __esDecorate(null, null, _minResponseTime_decorators, { kind: "field", name: "minResponseTime", static: false, private: false, access: { has: obj => "minResponseTime" in obj, get: obj => obj.minResponseTime, set: (obj, value) => { obj.minResponseTime = value; } }, metadata: _metadata }, _minResponseTime_initializers, _minResponseTime_extraInitializers);
            __esDecorate(null, null, _maxResponseTime_decorators, { kind: "field", name: "maxResponseTime", static: false, private: false, access: { has: obj => "maxResponseTime" in obj, get: obj => obj.maxResponseTime, set: (obj, value) => { obj.maxResponseTime = value; } }, metadata: _metadata }, _maxResponseTime_initializers, _maxResponseTime_extraInitializers);
            __esDecorate(null, null, _minRecordsAffected_decorators, { kind: "field", name: "minRecordsAffected", static: false, private: false, access: { has: obj => "minRecordsAffected" in obj, get: obj => obj.minRecordsAffected, set: (obj, value) => { obj.minRecordsAffected = value; } }, metadata: _metadata }, _minRecordsAffected_initializers, _minRecordsAffected_extraInitializers);
            __esDecorate(null, null, _maxRecordsAffected_decorators, { kind: "field", name: "maxRecordsAffected", static: false, private: false, access: { has: obj => "maxRecordsAffected" in obj, get: obj => obj.maxRecordsAffected, set: (obj, value) => { obj.maxRecordsAffected = value; } }, metadata: _metadata }, _maxRecordsAffected_initializers, _maxRecordsAffected_extraInitializers);
            __esDecorate(null, null, _deviceType_decorators, { kind: "field", name: "deviceType", static: false, private: false, access: { has: obj => "deviceType" in obj, get: obj => obj.deviceType, set: (obj, value) => { obj.deviceType = value; } }, metadata: _metadata }, _deviceType_initializers, _deviceType_extraInitializers);
            __esDecorate(null, null, _clientApplication_decorators, { kind: "field", name: "clientApplication", static: false, private: false, access: { has: obj => "clientApplication" in obj, get: obj => obj.clientApplication, set: (obj, value) => { obj.clientApplication = value; } }, metadata: _metadata }, _clientApplication_initializers, _clientApplication_extraInitializers);
            __esDecorate(null, null, _geolocation_decorators, { kind: "field", name: "geolocation", static: false, private: false, access: { has: obj => "geolocation" in obj, get: obj => obj.geolocation, set: (obj, value) => { obj.geolocation = value; } }, metadata: _metadata }, _geolocation_initializers, _geolocation_extraInitializers);
            __esDecorate(null, null, _timeRange_decorators, { kind: "field", name: "timeRange", static: false, private: false, access: { has: obj => "timeRange" in obj, get: obj => obj.timeRange, set: (obj, value) => { obj.timeRange = value; } }, metadata: _metadata }, _timeRange_initializers, _timeRange_extraInitializers);
            __esDecorate(null, null, _accessPurpose_decorators, { kind: "field", name: "accessPurpose", static: false, private: false, access: { has: obj => "accessPurpose" in obj, get: obj => obj.accessPurpose, set: (obj, value) => { obj.accessPurpose = value; } }, metadata: _metadata }, _accessPurpose_initializers, _accessPurpose_extraInitializers);
            __esDecorate(null, null, _minimumNecessary_decorators, { kind: "field", name: "minimumNecessary", static: false, private: false, access: { has: obj => "minimumNecessary" in obj, get: obj => obj.minimumNecessary, set: (obj, value) => { obj.minimumNecessary = value; } }, metadata: _metadata }, _minimumNecessary_initializers, _minimumNecessary_extraInitializers);
            __esDecorate(null, null, _patientConsent_decorators, { kind: "field", name: "patientConsent", static: false, private: false, access: { has: obj => "patientConsent" in obj, get: obj => obj.patientConsent, set: (obj, value) => { obj.patientConsent = value; } }, metadata: _metadata }, _patientConsent_initializers, _patientConsent_extraInitializers);
            __esDecorate(null, null, _emergencyAccess_decorators, { kind: "field", name: "emergencyAccess", static: false, private: false, access: { has: obj => "emergencyAccess" in obj, get: obj => obj.emergencyAccess, set: (obj, value) => { obj.emergencyAccess = value; } }, metadata: _metadata }, _emergencyAccess_initializers, _emergencyAccess_extraInitializers);
            __esDecorate(null, null, _exportFormat_decorators, { kind: "field", name: "exportFormat", static: false, private: false, access: { has: obj => "exportFormat" in obj, get: obj => obj.exportFormat, set: (obj, value) => { obj.exportFormat = value; } }, metadata: _metadata }, _exportFormat_initializers, _exportFormat_extraInitializers);
            __esDecorate(null, null, _includeAdditionalData_decorators, { kind: "field", name: "includeAdditionalData", static: false, private: false, access: { has: obj => "includeAdditionalData" in obj, get: obj => obj.includeAdditionalData, set: (obj, value) => { obj.includeAdditionalData = value; } }, metadata: _metadata }, _includeAdditionalData_initializers, _includeAdditionalData_extraInitializers);
            __esDecorate(null, null, _anonymizePatientData_decorators, { kind: "field", name: "anonymizePatientData", static: false, private: false, access: { has: obj => "anonymizePatientData" in obj, get: obj => obj.anonymizePatientData, set: (obj, value) => { obj.anonymizePatientData = value; } }, metadata: _metadata }, _anonymizePatientData_initializers, _anonymizePatientData_extraInitializers);
            if (_metadata) Object.defineProperty(_a, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        })(),
        _a;
})();
exports.AuditSearchDto = AuditSearchDto;
